---
- name: Configure NGINX webservers on EC2 hosts
  hosts: tag_Name_webserver
  remote_user: centos
  become: yes
  gather_facts: no
  roles:
    - { role: build_ssh_conf }
    - { role: configure_webserver, tags: ['configure_webserver'] }
